name: Pull Request CI Check
on: [pull_request]
jobs:
  build:
    name: Run CI
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - name: Check out the code
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
      - uses: 'docker/login-action@v3'
        with:
          registry: 'vsphere-docker-dev-local.usw5.packages.broadcom.com' # or REGION.docker.pkg.dev
          username: '${{ secrets.JFROG_USER }}'
          password: '${{ secrets.JFROG_PASSWORD }}'
      # Only try to publish the container image from the root repo; forks don't have permission to do so and will always get failures.
      - name: Publish container image
        if: github.repository == 'vmware-tanzu/velero'
        run: |
          sudo swapoff -a
          sudo rm -f /mnt/swapfile
          docker system prune -a --force
              
          # Build and push Velero image to docker registry
          docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASSWORD }}
          ./hack/docker-push.sh

